print('========== UI 系统测试开始 ==========',CS2LUA_API_VERSION)

local group=ui.create('UI Test','General',1)
local enabled=group:switch('Enable feature',true)
local amount=group:slider('Amount',0,100,50,1,'%')
local mode=group:combo('Mode',{'Legit','Rage','Visual'})
local choice=group:selectable('Target',{'Closest','Lowest HP','Distance'})
local nickname=group:input('Nickname','catgirl')
local hotkey=group:hotkey('Hotkey',0x24)
group:label('CS2LuaPlugin Neverlose-style UI')

enabled:set_callback(function()
  print('[成功] switch callback 功能正常，value=',enabled:get())
end)
amount:set_callback(function()
  print('[成功] slider callback 功能正常，value=',amount:get())
end)
mode:set_callback(function()
  print('[成功] combo callback 功能正常，index=',mode:get())
end)
choice:set_callback(function()
  local selected=choice:get()
  assert(type(selected)=='table','selectable:get() 应返回已选项目 table，实际为 '..type(selected))
  print('[成功] selectable 多选 callback 功能正常，数量=',#selected,
    'Closest=',choice:get('Closest'),'Lowest HP=',choice:get(2),'Distance=',choice:get('Distance'))
end)
nickname:set_callback(function()
  print('[成功] input callback 功能正常，text=',nickname:get())
end)
group:button('Run UI test',function()
  print('[成功] button callback 功能正常')
  print('[成功] MenuItem get/id/list/type 功能正常',enabled:get(),enabled:id(),mode:type(),#mode:list())
end)

print('[成功] ui.create/MenuGroup/MenuItem 创建功能正常')
print('[等待] 脚本列表前应出现齿轮；点击齿轮进入脚本菜单并操作控件')
